config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
    resources :messages
  end

  resources :bookings
  get 'registrations/create'
  get 'registrations/update'

  resources :charges
  resources :suburbs
  resources :pharmacies
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :suburb
  has_many :booking

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit( :first_name, :last_name, :address, :suburb_id, :medicare_no, :concession_no, :date_of_birth, :sex)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div> -->

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <!-- <div class="field">
    <%#= f.label :s %>
    <%#= f.text_field :s %>
  </div> -->

  <div class="field">
    <%= f.label :suburb %>
    <!-- <%= f.text_field :suburb_id %> -->
    <%= f.collection_select :suburb_id, Suburb.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :medicare_no %>
    <%= f.text_field :medicare_no %>
  </div>

  <div class="field">
    <%= f.label :concession_no %>
    <%= f.text_field :concession_no %>
  </div>

  <div class="field">
    <%= f.label :date_of_birth %>
    <%= f.date_select :date_of_birth, :start_year => 1900, :order => [:day, :month, :year] %>
  </div>
<!--
  <div class="field">
    <%= f.label :sex %>
    <%= f.text_field :sex %>
  </div> -->

  <div class="field">
    <%= f.label :sex %>
    <%= f.radio_button(:sex, "Female") %>
    <%= label_tag(:sex_female, "Female") %>
    <%= f.radio_button(:sex, "Male") %><%= label_tag(:sex_male, "Male") %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Suburb</th>
      <th>Medicare no</th>
      <th>Concession no</th>
      <th>Date of birth</th>
      <th>Sex</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user.email %></td>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.address %></td>
        <td><%= profile.suburb_id %></td>
        <td><%= profile.medicare_no %></td>
        <td><%= profile.concession_no %></td>
        <td><%= profile.date_of_birth %></td>
        <td><%= profile.sex %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @profile.user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @profile.suburb_id %>
</p>

<p>
  <strong>Medicare no:</strong>
  <%= @profile.medicare_no %>
</p>

<p>
  <strong>Concession no:</strong>
  <%= @profile.concession_no %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @profile.date_of_birth %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @profile.sex %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>