config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
    resources :messages
  end

  resources :bookings
  get 'registrations/create'
  get 'registrations/update'

  resources :charges
  resources :suburbs
  resources :pharmacies
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/models/suburb.rb
class Suburb < ApplicationRecord

  scope :name_eq, -> (name) { where('lower(name) = lower(?)', name) }
  
end

app/controllers/suburbs_controller.rb
class SuburbsController < ApplicationController
  before_action :set_suburb, only: [:show, :edit, :update, :destroy]

  # GET /suburbs
  # GET /suburbs.json
  def index
    @suburbs = Suburb.all
  end

  # GET /suburbs/1
  # GET /suburbs/1.json
  def show
  end

  # GET /suburbs/new
  def new
    @suburb = Suburb.new
  end

  # GET /suburbs/1/edit
  def edit
  end

  # POST /suburbs
  # POST /suburbs.json
  def create
    @suburb = Suburb.new(suburb_params)

    respond_to do |format|
      if @suburb.save
        format.html { redirect_to @suburb, notice: 'Suburb was successfully created.' }
        format.json { render :show, status: :created, location: @suburb }
      else
        format.html { render :new }
        format.json { render json: @suburb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suburbs/1
  # PATCH/PUT /suburbs/1.json
  def update
    respond_to do |format|
      if @suburb.update(suburb_params)
        format.html { redirect_to @suburb, notice: 'Suburb was successfully updated.' }
        format.json { render :show, status: :ok, location: @suburb }
      else
        format.html { render :edit }
        format.json { render json: @suburb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suburbs/1
  # DELETE /suburbs/1.json
  def destroy
    @suburb.destroy
    respond_to do |format|
      format.html { redirect_to suburbs_url, notice: 'Suburb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suburb
      @suburb = Suburb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suburb_params
      params.require(:suburb).permit(:name)
    end
end

app/helpers/suburbs_helper.rb
module SuburbsHelper
end

app/views/suburbs/_form.html.erb
<%= form_for(suburb) do |f| %>
  <% if suburb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(suburb.errors.count, "error") %> prohibited this suburb from being saved:</h2>

      <ul>
      <% suburb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suburbs/edit.html.erb
<h1>Editing Suburb</h1>

<%= render 'form', suburb: @suburb %>

<%= link_to 'Show', @suburb %> |
<%= link_to 'Back', suburbs_path %>

app/views/suburbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Suburbs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suburbs.each do |suburb| %>
      <tr>
        <td><%= suburb.name %></td>
        <td><%= link_to 'Show', suburb %></td>
        <td><%= link_to 'Edit', edit_suburb_path(suburb) %></td>
        <td><%= link_to 'Destroy', suburb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Suburb', new_suburb_path %>

app/views/suburbs/new.html.erb
<h1>New Suburb</h1>

<%= render 'form', suburb: @suburb %>

<%= link_to 'Back', suburbs_path %>

app/views/suburbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @suburb.name %>
</p>

<%= link_to 'Edit', edit_suburb_path(@suburb) %> |
<%= link_to 'Back', suburbs_path %>