config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
    resources :messages
  end

  resources :bookings
  get 'registrations/create'
  get 'registrations/update'

  resources :charges
  resources :suburbs
  resources :pharmacies
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :profile
  belongs_to :pharmacy
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?)
    OR (conversations.sender_id = ? AND conversations.recipient_id = ?)",
    sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%d/%m/%y at %l:%M %p")
  end
  
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  belongs_to :user
  belongs_to :suburb
  has_many :booking

  validates :address, presence: true

  geocoded_by :full_address, latitude: :lat, longitude: :lng
  after_validation :geocode

  attr_accessor :avatar
  mount_uploader :avatar, AvatarUploader

  def full_address
    [address, suburb.name].join(', ')
  end

  def self.search(search)
    where("suburb LIKE ?", "#{search}")
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :suburb
  has_many :booking

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  def patient?
    name == "Patient"
  end

  def pharmacy?
    name == "Pharmacy"
  end
end

app/models/suburb.rb
class Suburb < ApplicationRecord

  scope :name_eq, -> (name) { where('lower(name) = lower(?)', name) }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  belongs_to :role
  has_one :pharmacy

  # attr_accessor :avatar
  # mount_uploader :avatar, AvatarUploader
  #
  # before_create :set_role
  #
  # private
  #   def set_role
  #
  #   end

end

class User
  def pharmacy?
    pharmacy.present?
  end

  def display_name
    if pharmacy?
      pharmacy.name
    else
      profile.first_name
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create

    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'aud'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def new
  end

  def index
    @user = current_user
  end

  def create
  end
end

app/controllers/suburbs_controller.rb
class SuburbsController < ApplicationController
  before_action :set_suburb, only: [:show, :edit, :update, :destroy]

  # GET /suburbs
  # GET /suburbs.json
  def index
    @suburbs = Suburb.all
  end

  # GET /suburbs/1
  # GET /suburbs/1.json
  def show
  end

  # GET /suburbs/new
  def new
    @suburb = Suburb.new
  end

  # GET /suburbs/1/edit
  def edit
  end

  # POST /suburbs
  # POST /suburbs.json
  def create
    @suburb = Suburb.new(suburb_params)

    respond_to do |format|
      if @suburb.save
        format.html { redirect_to @suburb, notice: 'Suburb was successfully created.' }
        format.json { render :show, status: :created, location: @suburb }
      else
        format.html { render :new }
        format.json { render json: @suburb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suburbs/1
  # PATCH/PUT /suburbs/1.json
  def update
    respond_to do |format|
      if @suburb.update(suburb_params)
        format.html { redirect_to @suburb, notice: 'Suburb was successfully updated.' }
        format.json { render :show, status: :ok, location: @suburb }
      else
        format.html { render :edit }
        format.json { render json: @suburb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suburbs/1
  # DELETE /suburbs/1.json
  def destroy
    @suburb.destroy
    respond_to do |format|
      format.html { redirect_to suburbs_url, notice: 'Suburb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suburb
      @suburb = Suburb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suburb_params
      params.require(:suburb).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/suburbs_helper.rb
module SuburbsHelper
end

app/views/layouts/_nav.html.erb
<nav>
  <!-- class="navbar-text pull-right" -->
  <% if user_signed_in? %>
  Logged in as <%= current_user.email %>
  <br>
  <br>
    <% if current_user.role.pharmacy? %>
      <%= link_to "Create pharmacy", new_pharmacy_path, :class => "navbutton" %>
      <%#= link_to "Edit pharmacy", edit_pharmacy_path(@pharmacy), :class => "navbutton" %>
      <%= link_to "Messages", conversations_path, :class => "navbutton" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbutton" %>

    <% elsif current_user.role.patient? %>
      <%= link_to "Create profile", new_profile_path, :class => "navbutton" %>
      <%= link_to "Search pharmacies", pharmacies_path, :class => "navbutton" %>
      <%= link_to "Messages", conversations_path, :class => "navbutton" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbutton" %>

    <% end %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => "navbutton"%>
    <%= link_to "Login", new_user_session_path, :class => "navbutton" %>
  <% end %>
  <br>
  <br>


  <%# if current_user.has_role? :pharmacy %>
    <%#= link_to "Manage Pharmacy", pharmacy_path %>
  <%# end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panacea</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= render partial: 'layouts/nav' %>

  <div>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <!-- Can change class name after if required (copied from tutorial) -->
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </div>



    <%# unless current_user.profile.blank? %>
    <%#= render partial: 'layouts  /form', profile: @profile %>
    <%# end %>

    <!-- <% unless @user.blank? %>
    Email:<%#= @user.email %><br />
    Member Since:<%#= @user.created_at  %><br />
    <% end %> -->

    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>